version: '3.5'
services:
  client:
    build:
      context: ./client
    command: 'sh -c "npm run start"'
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - './client/src:/app/src'
      - './client/package.json:/app/package.json'
      - './client/package-lock.json:/app/package-lock.json'
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: 'sh -c "npm start"'
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - './api/src/:/app/src'
      - './api/package.json:/app/package.json'
      - './api/package-lock.json:/app/package-lock.json'
  postgres:
    container_name: postgres
    build:
      context: ./data/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://postgres:password@postgres:5432/bookstore
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: